version: '3.5'
services:
  multl-threaded-selenium-scrapping:  # Change this to a unique name for your service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:80"
    volumes:
      - ./config.json:/home/site/wwwroot/config.json